### ISSUE TITLE
BinaryAI install_ida_plugin failed when there need proxy

### ISSUE THREAD

**Issue by szlenghuangfei** [binaryai/sdk#107]
![image](https://user-images.githubusercontent.com/47766982/97958238-c550f480-1de7-11eb-8c21-7ff34b6d258a.png)

**Comment by nforest** [comment]
This is a known issue, we plan to fix it in the v0.3 release.

Because BinaryAI will have breaking changes in order to support the latest model on the server-side, then we use pypi.org to check the latest plugin version and ask users to upgrade to it on the client-side.

**Comment by GluttonYu** [comment]
After executing the 'binaryai install_ida_plugin' command, the file 'binaryai.cfg' is not installed.

**Comment by nforest** [comment]
> After executing the 'binaryai install_ida_plugin' command, the file 'binaryai.cfg' was not installed.

Actually, the `binaryai.cfg` file is created when you launch the plugin in IDA Pro for the first time.

BTW, it's better to discuss the new question in a different thread.
