### ISSUE TITLE
BinaryAI doesn't work in IDA64 of free version

### ISSUE THREAD

**Issue by Xelawk** [binaryai/sdk#119]
Does BinaryAI not support the IDA64 of free version? I completely follow the official instructions and still can't see the binaryai option in the toolbar

**Comment by nforest** [comment]
> Does BinaryAI not support the IDA64 of free version? I completely follow the official instructions and still can't see the binaryai option in the toolbar

If I remember correctly, IDA Free version does not support external plugins and it has limited decompiler support, so that binaryai is not suitable for IDA free version.

Thanks!
