### ISSUE TITLE
Can't apply for token

### ISSUE THREAD

**Issue by Adalsteinnjons** [binaryai/sdk#122]
![image](https://user-images.githubusercontent.com/28142119/166491806-1af29158-3343-468e-bc6f-9f4d307e20ee.png)

**Comment by jimmy0435** [comment]
I faced the same problem.

**Comment by Excelsior-007** [comment]
I've also got the same problem,and I don't know where else I can get the token.

**Comment by davendu** [comment]
Hi @Adalsteinnjons @jimmy0435 @Excelsior-007 

I'm regret to say that we are going to deprecate current version's service. I'm going to offline all related services later.

We are now working on a new version based on our latest work so this offline is not permanent. We just want to focus on improving the new generation ;)
