### ISSUE TITLE
The need of analysing Python binary file similarity tools

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [binaryai/sdk#123]
![image](https://user-images.githubusercontent.com/82520400/200263803-3da85f4f-6e53-4a6e-a940-6751832a0914.png)
Hi, 
I need a tool to analyze an python project by binary file or scource code, and I saw you say that you are currently working on a new version. 
Dose it published yet? Pleace tell me, thank you!

**Comment by davendu** [comment]
Hi, we made a new update to the README in 2023:

> - You can first upload your binary to [binaryai.net](https://binaryai.net) and download the json file by clicking the BinaryAI similarity button when the analysis finishes. You can use our latest [plugin](https://github.com/binaryai/plugins) to load result in Ghidra/IDA Pro.
