### ISSUE TITLE
The binaryai cause my ida crash

### ISSUE THREAD

**Issue by WinMin** [binaryai/sdk#84]
The IDA will crash after I drag a new binary to the window when there has already been an instance.

![image](https://user-images.githubusercontent.com/18380453/91050902-ea8bee80-e651-11ea-9e91-75c3a5edef43.png)

**Comment by WinMin** [comment]
![image](https://user-images.githubusercontent.com/18380453/91051180-53736680-e652-11ea-8063-3d7197d422d1.png)

**Comment by DogeWatch** [comment]
what's your IDA version and platform?

**Comment by aundro** [comment]
Hi, this is Arnaud Diederen, from Hex-Rays.
We'll investigate this issue and get back to you, as it is possible that the culprit is IDA itself, not binaryai.

I'll keep you posted.

**Comment by WinMin** [comment]
> what's your IDA version and platform?

IDA 7.5 windows

**Comment by aundro** [comment]
Hi again,

so, it turns out that the problem is in the binaryai plugin, but it didn't show until 7.5.
Simply put, the plugin shouldn't return `ida_loader.PLUGIN_OK`, but rather `ida_loader.PLUGIN_KEEP`.

In fact, `ida_loader.PLUGIN_OK` is really meant for non-`ida_loader.PLUGIN_FIX` plugins. Plugins using `ida_loader.PLUGIN_FIX` should always return `ida_loader.PLUGIN_KEEP` (or `ida_loader.PLUGIN_SKIP`)

**Comment by nforest** [comment]
> Hi again,
> 
> so, it turns out that the problem is in the binaryai plugin, but it didn't show until 7.5.
> Simply put, the plugin shouldn't return `ida_loader.PLUGIN_OK`, but rather `ida_loader.PLUGIN_KEEP`.
> 
> In fact, `ida_loader.PLUGIN_OK` is really meant for non-`ida_loader.PLUGIN_FIX` plugins. Plugins using `ida_loader.PLUGIN_FIX` should always return `ida_loader.PLUGIN_KEEP` (or `ida_loader.PLUGIN_SKIP`)

Great, thanks for your professional investigation.
I can fix it later, or you're welcome to fork and pull a request.

**Comment by aundro** [comment]
I think it's easier (as in: less noise) if I just let you handle it.

**Comment by nforest** [comment]
> I think it's easier (as in: less noise) if I just let you handle it.

sure, no problem.
